<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>
    <ItemGroup>
        <Compile Remove="examples/**/*.cs" />
        <Compile Remove="tests/**/*.cs" />
        <Compile Remove="benchmarks/**/*.cs" />
        <None Remove="examples/**/*" />
        <None Remove="tests/**/*" />
        <None Remove="benchmarks/**/*" />
    </ItemGroup>
</Project>