#pragma once

#include <cstdint>

inline constexpr uint8_t NOTSET = 0;
inline constexpr uint8_t TRACE = 5;
inline constexpr uint8_t DEBUG = 10;
inline constexpr uint8_t INFO = 20;
inline constexpr uint8_t SUCCESS = 25;
inline constexpr uint8_t WARNING = 30;
inline constexpr uint8_t WARN = WARNING;
inline constexpr uint8_t ERROR = 40;
inline constexpr uint8_t CRITICAL = 50;
inline constexpr uint8_t FATAL = CRITICAL;
inline constexpr uint8_t EXCEPTION = 60;
inline constexpr uint8_t NOLOG = 100;

// Stable C++ include path for the cxxfastlogging bridge.
//
// The actual bindings are generated by the `cxx` crate from `src/lib.rs` at
// build time. This header just forwards to the generated header so that
// consumers can write:
//
//     #include "cxxfastlogging/h/fastlogging.h"
//
// instead of depending on cxx's generated include path directly. The build
// command must add cxx's generated include directory to the compiler path.
#include "cxxfastlogging/src/lib.rs.h"
