#pragma once

// Stable C++ include path for the cxxfastlogging bridge.
//
// The actual bindings are generated by the `cxx` crate from `src/lib.rs` at
// build time. This header just forwards to the generated header so that
// consumers can write:
//
//     #include "cxxfastlogging/h/fastlogging.h"
//
// instead of depending on cxx's generated include path directly.
#include "cxxfastlogging/src/lib.rs.h"
