[build]
rustflags = ["-C", "target-cpu=x86-64-v3", "-Zshare-generics=n"]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"


[target.wasm32-unknown-unknown]
rustflags = ["-Zshare-generics=n"]

[target.wasm32-wasi]
rustflags = ["-Zshare-generics=n"]
