from collections.abc import Callable as CallableABC

# Log level constants
EXCEPTION: int = 60
CRITICAL: int = 50
FATAL: int = 50
ERROR: int = 40
WARNING: int = 30
WARN: int = 30
SUCCESS: int = 25
INFO: int = 20
DEBUG: int = 10
TRACE: int = 5
NOTSET: int = 0
__version__: str

class Level2Sym:
    NotSet: Level2Sym = ...
    Debug: Level2Sym = ...
    Info: Level2Sym = ...
    Warning: Level2Sym = ...
    Error: Level2Sym = ...
    Critical: Level2Sym = ...
    Exception: Level2Sym = ...
    NoLog: Level2Sym = ...
    def __init__(self, value: int) -> None: ...
    @property
    def value(self) -> int: ...
    @property
    def name(self) -> str: ...

class LevelSyms:
    def __init__(self) -> None: ...
    @property
    def value(self) -> int: ...
    @property
    def name(self) -> str: ...

class MessageStructEnum:
    String: MessageStructEnum = ...
    Json: MessageStructEnum = ...
    Xml: MessageStructEnum = ...

class CompressionMethodEnum:
    Store: CompressionMethodEnum = ...
    Deflate: CompressionMethodEnum = ...
    Zstd: CompressionMethodEnum = ...
    Lzma: CompressionMethodEnum = ...

class EncryptionMethod: ...

class WriterTypeEnum:
    Root: WriterTypeEnum = ...
    Console: WriterTypeEnum = ...
    File: WriterTypeEnum = ...
    Files: WriterTypeEnum = ...
    Client: WriterTypeEnum = ...
    Clients: WriterTypeEnum = ...
    Server: WriterTypeEnum = ...
    Servers: WriterTypeEnum = ...
    Syslog: WriterTypeEnum = ...
    Callback: WriterTypeEnum = ...
    OpenTelemetry: WriterTypeEnum = ...

class WriterConfigEnum:
    Root: WriterConfigEnum
    Console: WriterConfigEnum
    File: WriterConfigEnum
    Client: WriterConfigEnum
    Server: WriterConfigEnum
    Syslog: WriterConfigEnum
    Callback: WriterConfigEnum
    OpenTelemetry: WriterConfigEnum

class ExtConfig:
    def __init__(
        self,
        structured: MessageStructEnum,
        hostname: bool,
        pname: bool,
        pid: bool,
        tname: bool,
        tid: bool,
    ) -> None: ...

class RootConfig: ...

class ConsoleWriterConfig:
    def __init__(self, level: int, colors: bool) -> None: ...

class FileWriterConfig:
    def __init__(
        self,
        level: int,
        path: str,
        size: int | None = None,
        backlog: int | None = None,
        timeout: float | None = None,
        time: float | None = None,
        compression: CompressionMethodEnum | None = None,
    ) -> None: ...

class ServerConfig:
    def __init__(
        self, level: int, address: str, key: EncryptionMethod | None = None
    ) -> None: ...

class ClientWriterConfig:
    def __init__(
        self, level: int, address: str, key: EncryptionMethod | None = None
    ) -> None: ...

class SyslogWriterConfig:
    def __init__(
        self,
        level: int,
        hostname: str | None = None,
        pname: str | None = None,
        pid: int | None = None,
    ) -> None: ...

class CallbackWriterConfig:
    def __init__(self, level: int, callback: CallableABC) -> None: ...
    def set_callback(self, callback: CallableABC | None = None) -> None: ...

class OpenTelemetryWriterConfig:
    def __init__(self, level: int, endpoint: str, service_name: str) -> None: ...

class LoggingError(Exception): ...

class Logging:
    def __init__(
        self,
        level: int = ...,
        domain: str | None = None,
        configs: (
            list[
                WriterConfigEnum
                | RootConfig
                | ConsoleWriterConfig
                | FileWriterConfig
                | ClientWriterConfig
                | ServerConfig
                | SyslogWriterConfig
                | CallbackWriterConfig
                | OpenTelemetryWriterConfig
            ]
            | None
        ) = None,
        ext_config: ExtConfig | None = None,
        config_path: str | None = None,
        indent: tuple[int, int, int] | None = None,
    ) -> None: ...
    def shutdown(self, now: bool = False) -> None: ...
    def set_level(self, wid: int, level: int) -> None: ...
    def set_domain(self, domain: str) -> None: ...
    def set_level2sym(self, level2sym: LevelSyms) -> None: ...
    def set_ext_config(self, ext_config: ExtConfig) -> None: ...
    def add_logger(self, logger: Logger) -> None: ...
    def remove_logger(self, logger: Logger) -> None: ...
    def set_root_writer(self, config: WriterConfigEnum) -> None: ...
    def add_writer(
        self,
        config: (
            RootConfig
            | ConsoleWriterConfig
            | FileWriterConfig
            | ClientWriterConfig
            | ServerConfig
            | SyslogWriterConfig
            | CallbackWriterConfig
            | OpenTelemetryWriterConfig
            | WriterConfigEnum
        ),
    ) -> int: ...
    def remove_writer(self, wid: int) -> WriterConfigEnum | None: ...
    def add_writers(
        self,
        configs: list[
            RootConfig
            | ConsoleWriterConfig
            | FileWriterConfig
            | ClientWriterConfig
            | ServerConfig
            | SyslogWriterConfig
            | CallbackWriterConfig
            | WriterConfigEnum
        ],
    ) -> list[int]: ...
    def remove_writers(
        self, wids: list[int] | None = None
    ) -> list[WriterConfigEnum]: ...
    def enable(self, wid: int) -> None: ...
    def disable(self, wid: int) -> None: ...
    def enable_type(self, typ: WriterTypeEnum) -> None: ...
    def disable_type(self, typ: WriterTypeEnum) -> None: ...
    def sync(
        self, types: list[WriterTypeEnum] | None = None, timeout: float | None = None
    ) -> None: ...
    def sync_all(self, timeout: float | None = None) -> None: ...
    def rotate(self, path: str | None = None) -> None: ...
    def set_encryption(self, wid: int, key: EncryptionMethod) -> None: ...
    def get_writer_config(self, wid: int) -> WriterConfigEnum | None: ...
    def get_server_config(self, wid: int) -> ServerConfig: ...
    def get_server_configs(self) -> dict[int, ServerConfig]: ...
    def get_root_server_address_port(self) -> str | None: ...
    def get_server_addresses_ports(self) -> dict[int, str]: ...
    def get_server_addresses(self) -> dict[int, str]: ...
    def get_server_ports(self) -> dict[int, int]: ...
    def get_server_auth_key(self) -> EncryptionMethod: ...
    def get_config_string(self) -> str: ...
    def save_config(self, path: str | None = None) -> None: ...
    def trace(self, msg: str) -> None: ...
    def debug(self, msg: str) -> None: ...
    def info(self, msg: str) -> None: ...
    def success(self, msg: str) -> None: ...
    def warning(self, msg: str) -> None: ...
    def error(self, msg: str) -> None: ...
    def critical(self, msg: str) -> None: ...
    def fatal(self, msg: str) -> None: ...
    def exception(self, msg: str) -> None: ...
    def set_debug(self, debug: int) -> None: ...

class Logger:
    def __init__(
        self,
        level: int,
        domain: str,
        indent: tuple[int, int, int] | None = None,
        tname: bool | None = None,
        tid: bool | None = None,
    ) -> None: ...
    def set_level(self, level: int) -> None: ...
    def level(self) -> int: ...
    def set_domain(self, domain: str) -> None: ...
    def trace(self, msg: str) -> None: ...
    def debug(self, msg: str) -> None: ...
    def info(self, msg: str) -> None: ...
    def success(self, msg: str) -> None: ...
    def warning(self, msg: str) -> None: ...
    def error(self, msg: str) -> None: ...
    def critical(self, msg: str) -> None: ...
    def fatal(self, msg: str) -> None: ...
    def exception(self, msg: str) -> None: ...

# Root-level module functions
def root_init() -> None: ...
def shutdown(now: bool = False) -> None: ...
def set_level(wid: int, level: int) -> None: ...
def set_root_level(level: int) -> None: ...
def set_domain(domain: str) -> None: ...
def set_level2sym(level2sym: LevelSyms) -> None: ...
def set_ext_config(ext_config: ExtConfig) -> None: ...
def add_logger(logger: Logger) -> None: ...
def remove_logger(logger: Logger) -> None: ...
def set_root_writer(config: WriterConfigEnum) -> None: ...
def add_writer(
    config: (
        RootConfig
        | ConsoleWriterConfig
        | FileWriterConfig
        | ClientWriterConfig
        | ServerConfig
        | SyslogWriterConfig
        | CallbackWriterConfig
        | OpenTelemetryWriterConfig
        | WriterConfigEnum
    ),
) -> int: ...
def remove_writer(wid: int) -> WriterConfigEnum | None: ...
def add_writers(
    configs: list[
        RootConfig
        | ConsoleWriterConfig
        | FileWriterConfig
        | ClientWriterConfig
        | ServerConfig
        | SyslogWriterConfig
        | CallbackWriterConfig
        | OpenTelemetryWriterConfig
        | WriterConfigEnum
    ],
) -> list[int]: ...
def remove_writers(wids: list[int] | None = None) -> list[WriterConfigEnum]: ...
def enable(wid: int) -> None: ...
def disable(wid: int) -> None: ...
def enable_type(typ: WriterTypeEnum) -> None: ...
def disable_type(typ: WriterTypeEnum) -> None: ...
def sync(
    types: list[WriterTypeEnum] | None = None, timeout: float | None = None
) -> None: ...
def sync_all(timeout: float | None = None) -> None: ...
def rotate(path: str | None = None) -> None: ...
def set_encryption(wid: int, key: EncryptionMethod) -> None: ...
def get_writer_config(wid: int) -> WriterConfigEnum | None: ...
def get_server_config(wid: int) -> ServerConfig: ...
def get_server_configs() -> dict[int, ServerConfig]: ...
def get_server_addresses_ports() -> dict[int, str]: ...
def get_server_addresses() -> dict[int, str]: ...
def get_server_ports() -> dict[int, int]: ...
def get_server_auth_key() -> EncryptionMethod: ...
def get_config_string() -> str: ...
def save_config(path: str | None = None) -> None: ...
def get_parent_pid() -> int | None: ...
def get_parent_client_writer_config() -> ClientWriterConfig | None: ...
def get_parent_pid_client_writer_config() -> tuple[int, ClientWriterConfig] | None: ...
def trace(msg: str) -> None: ...
def debug(msg: str) -> None: ...
def info(msg: str) -> None: ...
def success(msg: str) -> None: ...
def warning(msg: str) -> None: ...
def error(msg: str) -> None: ...
def critical(msg: str) -> None: ...
def fatal(msg: str) -> None: ...
def exception(msg: str) -> None: ...
def set_debug(debug: int) -> None: ...
