[package]
name = "jfastlogging"
version = "0.3.0"
authors = ["Martin Bammer <mrbm74@gmail.com>"]
edition = "2021"

[dependencies]
jni = "0.21"
once_cell = "1.19"
fastlogging = { path = "../fastlogging" }

[lib]
crate-type = ["cdylib"]
