[package]
name = "jfastlogging"
version = "0.3.0"
authors = ["Martin Bammer <mrbm74@gmail.com>"]
edition = "2024"

[dependencies]
jni = "0.21"
once_cell = "1.21"
fastlogging = { path = "../fastlogging" }

[lib]
crate-type = ["cdylib"]
